version: '3'

services:
  nginx_proxy:
    container_name: nginx_proxy
    hostname: nginx_proxy
    build: ./proxy
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80/tcp"
      - "${IP:-0.0.0.0}:443:443/tcp"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-1m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-2}

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
    logging:
      driver: ${LETS_LOG_DRIVER:-json-file}
      options:
        max-size: ${LETS_WEB_LOG_MAX_SIZE:-1m}
        max-file: ${LETS_WEB_LOG_MAX_FILE:-2}

volumes:
  certs:
  vhost.d:
  html:

networks:
  frontend:
    external:
      name: frontend
